/**
 * Permissions & Role Definitions - Single Source of Truth
 */

export const ROLES = {
  CUSTOMER: 'customer',
  PROVIDER: 'provider'
};

export const PERMISSIONS = {
  // Customer Permissions
  CREATE_OPPORTUNITY: [ROLES.CUSTOMER],
  MANAGE_MY_OPPORTUNITIES: [ROLES.CUSTOMER],
  MANAGE_APPLICATION_STATUS: [ROLES.CUSTOMER],
  CREATE_REVIEW: [ROLES.CUSTOMER],

  // Provider Permissions
  MANAGE_SERVICES: [ROLES.PROVIDER],
  MANAGE_PRODUCTS: [ROLES.PROVIDER],
  PROVIDER_ONBOARDING: [ROLES.PROVIDER],
  APPLY_TO_OPPORTUNITY: [ROLES.PROVIDER],
  VIEW_MY_APPLICATIONS: [ROLES.PROVIDER],
  WITHDRAW_APPLICATION: [ROLES.PROVIDER],

  // Shared Authenticated Permissions
  VIEW_PUBLIC_DISCOVERY: [ROLES.CUSTOMER, ROLES.PROVIDER],
  UPDATE_OWN_PROFILE: [ROLES.CUSTOMER, ROLES.PROVIDER]
};
